### ISSUE TITLE
[Feature] Add status and player control widgets to Notification Bar and lock screen

### ISSUE THREAD

**Issue by Korb** [gokadzev/Musify#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

UI Improvements

### Credits

?

### Pain

While playing music, neither the lock screen nor the notification bar displays a widget with the data of the current song and there are no pause buttons, go to the next and previous song, as well as a button to close the application and unload it from memory.

### Suggested Solution

Widgets should be displayed so that you do not have to launch the player with a shortcut from the desktop every time.

### Useful resources/references

Vivo T1, Android 13

**Comment by gokadzev** [comment]
@Korb i think you mean media notification and yes, i noticed that its implementation has problem so i'm assigning it as bug. (tell me if i understood it wrong)

**Comment by gokadzev** [comment]
@Korb check if it's fixed in the latest version.

**Comment by Korb** [comment]
> check if it's fixed in the latest version.

v3.8.0 from F-Droid — after granting all permissions to the application, control from the notification panel and the lock screen is still not possible:
![Screenshot_20230116_102319](https://user-images.githubusercontent.com/3509797/212621389-d91b9912-649e-44cf-a6a6-f7e600a13057.png)

![Screenshot_20230116_102328](https://user-images.githubusercontent.com/3509797/212621393-972d887c-b4a5-4dda-8b17-805e8bfba08d.jpg)

![Screenshot_20230116_102333](https://user-images.githubusercontent.com/3509797/212621397-c783525e-2b11-4673-a83d-c8a89035ee89.jpg)

![Screenshot_20230116_102341](https://user-images.githubusercontent.com/3509797/212621398-d028c78e-bfe1-4c39-88d6-479b1841181f.jpg)

```
Версия ОС: Funtouch OS 13 Global
Модель: V2153
Версия аппаратного обеспечения: МР_0.1
Номер сборки: PD2201OF_EX_A_13.1.13.1.W20.V000L1
Прошивка модуля связи: MPSS.HA.1.1.С2-00012-KD_ALL_PACK-1.6347.66
Версия ядра: 4.19.1 57-perf+ #1 Thu Dec 1 1 2:1 5:36 CST 2022
Время компиляции: 1 дек. 2022 г. 07:03:09
Обновление системы безопасности Android: 1 декабря 2022 г.
Обновление системы через Google Play: 1 ноября 2022 г.
```
